spring:
  application:
    name: workspace-service
  # integrate with postgres
  datasource:
    url: jdbc:postgresql://188.166.255.182:8084/workspace
    username: workspace
    password: 8084

  elasticsearch:
    uris: http://209.38.56.20:9200
    username: stacknote
    password: stacknote
    connection-timeout: 10s
    socket-timeout: 30s

  #  #spring data jpa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  #  #Resource server configuration
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://keycloak.jelay.site/realms/stack-notes
          jwk-set-uri: ${spring.security.oauth2.resource-server.jwt.issuer-uri}/protocol/openid-connect/certs
  # circuit breaker with feign
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      compression:
        response:
          enabled: true
        request:
          enabled: true
resilience4j:
  circuitbreaker:
    instances:
      UserClientgetUserByEmail:
        register-health-indicator: true
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 20
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        sliding-window-type: COUNT_BASED
      UserClientgetUserByIdStringUUID:
        register-health-indicator: true
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 20
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        sliding-window-type: COUNT_BASED
      NotificationClientsendNotificationToUserStringNotificationRequest:
        register-health-indicator: true
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 20
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        sliding-window-type: COUNT_BASED
      DocumentClientdeleteDocumentByWorkspaceIdStringUUID:
        register-health-indicator: true
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 20
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        sliding-window-type: COUNT_BASED

## Keycloak configuration
keycloak:
  auth-server-url: https://keycloak.jelay.site/
  realm: stack-notes
  credentials:
    client-id: stack-notes-client
    secret: tDbzKXKsHvvmFQAJ1bUSR87Dbia2ssfZ
    provider: secret

## connect with eureka server
eureka:
  client:
    service-url:
      defaultZone: https://eureka.jelay.site/eureka/  # Adjust for your Eureka server URL
  instance:
    prefer-ip-address: true


# feign client
document-service:
  url: https://document-service.jelay.site
notification-service:
  url: https://notification.jelay.site
user-service:
  url: https://userservice.jelay.site

## Swagger configuration
springdoc:
  swagger-ui:
    oauth:
      realm: stack-notes
      client-id: stack-notes-client
      client-secret: tDbzKXKsHvvmFQAJ1bUSR87Dbia2ssfZ
    tags-sorter: alpha
logging:
  level:
    org.example: debug
    feign: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, circuitbreakers
server:
  port: 8084